accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('owner_registration', views.owner_registration, name='owner_registration'),
    path('user_registration', views.user_registration, name='user_registration'),
    path('login_user', views.login_user, name='login_user'),
    path('logout_user', views.logout_user, name='logout_user'),
    path('manage_profile', views.manage_profile, name='manage_profile'),
    path('send_enquiries', views.send_enquiries, name='send_enquiries'),
    path('recieved_enquiries', views.recieved_enquiries, name='recieved_enquiries'),
    path('recieved_enquiries/enquiry_details/<int:enquiry_id>', views.enquiry_details, name='enquiry_details'),
    path('manage_properties', views.manage_properties, name='manage_properties'),
    path('manage_properties/delete/<int:property_id>', views.delete_property, name='delete_property'),
    path('manage_properties/book/<int:property_id>', views.book_property, name='book_property'),
    path('manage_properties/update/<int:property_id>', views.update_property, name='update_property'),
]

house_rental_system_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('properties/', include('properties.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    is_owner = models.BooleanField(default=False)
    is_user = models.BooleanField(default=False)
    contact_no = models.CharField(max_length=100, blank=False)
    address = models.TextField(blank=False)

    def __str__(self):
        return self.username

properties/models.py
from django.db import models
from datetime import datetime
from accounts.models import User

class Property(models.Model):
    property_title = models.CharField(max_length=200)
    bathrooms = models.IntegerField()
    bedrooms = models.IntegerField()
    rooms = models.IntegerField()
    price = models.IntegerField()
    garage = models.IntegerField(default=0)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=20)
    sqft = models.DecimalField(max_digits=5, decimal_places=1)
    is_featured = models.BooleanField(default=False)
    booked = models.BooleanField(default=False)
    main_image = models.ImageField(upload_to='photos/')
    image_1 = models.ImageField(upload_to='photos/')
    image_2 = models.ImageField(upload_to='photos/')
    image_3 = models.ImageField(upload_to='photos/')
    list_date = models.DateTimeField(default=datetime.now, blank=True)
    owner_id = models.ForeignKey(User, on_delete=models.CASCADE)

    # Amenities
    wifi = models.BooleanField(default=False)
    kitchen = models.BooleanField(default=False)
    parking = models.BooleanField(default=False)
    swimming_pool = models.BooleanField(default=False)
    air_conditioning = models.BooleanField(default=False)
    balcony = models.BooleanField(default=False)
    tv = models.BooleanField(default=False)
    laundry = models.BooleanField(default=False)
    elevator_access = models.BooleanField(default=False)

    def __str__(self):
        return self.property_title
    
class Enquiry(models.Model):
    property_id = models.ForeignKey(Property, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    enquiry_date = models.DateTimeField(default=datetime.now)
    
    def __str__(self):
        return self.message

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import User
from django.contrib import messages
from django.contrib import auth
from properties.models import Property, Enquiry

# Custom function
def registration(request, data, user_type):
        username = data['username']
        email_address = data['email-address']
        contact_no = data['contact-no']
        address = data['address']
        password = data['password']
        confirm_password = data['cpassword']
       
        if username == '' or email_address == '' or contact_no == '' or address == '' or password == '' or confirm_password == '':
            messages.error(request, "Please fill all the fields")
            # return HttpResponse('Please fill all the fields') 
        else:
            # check if passwords match
            if password == confirm_password:
            #     # check if username is taken
                if User.objects.filter(username=username).exists():
                    messages.error(request, "Username is taken")
                    # return HttpResponse('Username is taken')
                # check if email is being used
                else:
                    if User.objects.filter(email=email_address).exists():
                        messages.error(request, "Email is being used")
                        # return HttpResponse('Email is being used')
                    else:
                        if user_type == 'owner':
                            owner = User(is_owner=True, username=username, email=email_address, contact_no=contact_no, address=address)
                        elif user_type == 'user':
                             owner = User(is_user=True, username=username, email=email_address, contact_no=contact_no, address=address)
                        owner.set_password(password)
                        owner.save()
                        messages.success(request, 'Registered Successfully!')
                        # return HttpResponse('Registered Successfully!')
                        
            else:
                messages.error(request, 'Passwords should match')
                # return HttpResponse('Passwords should match')

def owner_registration(request):
    if request.method == 'POST':
        registration(request, request.POST, 'owner')

        
    return render(request, 'accounts/owner_registration.html')

def user_registration(request):
    if request.method == 'POST':
        registration(request, request.POST, 'user')
    return render(request, 'accounts/user_registration.html')

def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        if username == '' or password == '':
            messages.error(request, 'Please fill up the fields')
            return redirect('login_user')
        user = auth.authenticate(username=username, password=password)
        if user:
            auth.login(request, user)
            messages.success(request, 'Loggedin Successfully')
            return redirect('index')
        else:
            messages.error(request, 'Invalid Credentials')

    return render(request, 'accounts/login.html')

def logout_user(request):
    auth.logout(request)
    messages.success(request, 'Loggedout Successfully')
    return redirect('login_user')

def manage_profile(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email-address']
        contact_no = request.POST['contact-no']
        address = request.POST['address']
        if username == '' or email == '' or contact_no == '' or address == '':
            messages.error(request, 'Please fill up all the fields')
            return redirect('manage_profile')
        else:
            user = User.objects.get(id=request.user.id)
            user.username = username
            user.email = email
            user.contact_no = contact_no
            user.address = address
            user.save()
            messages.success(request, 'Profile updated successfully')
    return render(request, 'accounts/manage_profile.html')

def send_enquiries(request):
    enquiries = Enquiry.objects.filter(user_id=request.user.id)
    context = {
        'enquiries': enquiries,
    }
    return render(request, 'accounts/send_enquiries.html', context)

def recieved_enquiries(request):
    enquiries = Enquiry.objects.filter(property_id__owner_id=request.user.id)
    context = {
        'enquiries': enquiries,
    }
    return render(request, 'accounts/recieved_enquiries.html', context)

def enquiry_details(request, enquiry_id):
    enquiry = Enquiry.objects.get(id=enquiry_id)
    context = {
        'enquiry': enquiry,
    }
    return render(request, 'accounts/enquiry_details.html', context)

def manage_properties(request):
    if request.user.is_authenticated and request.user.is_owner:
        owner_properties = Property.objects.filter(owner_id=request.user.id)
        context = {'owner_properties': owner_properties}
        return render(request, 'accounts/manage_properties.html', context)
    else:
        return redirect('login_user')
    
def delete_property(request, property_id):
    deleted_property = Property.objects.get(id=property_id)
    deleted_property.delete()
    messages.success(request, 'Property deleted successfully')
    return redirect('manage_properties')

def book_property(request, property_id):
    booked_property = Property.objects.get(id=property_id)
    booked_property.delete()
    messages.success(request, 'That property has being booked/rented')
    return redirect('manage_properties')

def update_property(request, property_id):
    updated_property = Property.objects.get(id=property_id)
    context = {
        'updated_property': updated_property,
    }
    return render(request, 'accounts/update_property.html', context)

templates/accounts/enquiry_details.html
{% extends 'base.html' %}


{% block title %}
    Enquiry Detail
{% endblock title %}
    

{% block content %}

<div class="container my-4">
   <h2>Enquiry Details</h2>
   <table class="table my-4">
    <tbody>
      <tr>
        <td><strong>Name</strong></td>
        <td>{{ enquiry.user_id.username }}</td>
      </tr>
      <tr>
        <td><strong>Property Title</strong></td>
        <td>{{ enquiry.property_id.property_title }}</td>
      </tr>
      <tr>
        <td><strong>Email Address</strong></td>
        <td>{{ enquiry.user_id.email }}</td>
      </tr>
      <tr>
        <td><strong>Contact No</strong></td>
        <td>{{ enquiry.user_id.contact_no }}</td>
      </tr>
      <tr>
        <td><strong>Address</strong></td>
        <td>{{ enquiry.user_id.address }}</td>
      </tr>
      <tr>
        <td><strong>Message</strong></td>
        <td>{{ enquiry.message }}</td>
      </tr>
      <tr>
        <td><strong>Enquiry Date</strong></td>
        <td>{{ enquiry.enquiry_date }}</td>
      </tr>
      <tr>
        <td><strong>View Property</strong></td>
        <td><a href="{% url 'property' enquiry.property_id.id  %}"><button type="button" class="btn btn-light">View Property</button></a></td>
      </tr>
    </tbody>
  </table>
</div>

{% endblock content %}

templates/accounts/login.html
{% extends 'base.html' %}


{% block title %}
    Login
{% endblock title %}
    

{% block content %}

<div class="container my-4">
    <h2 class="my-4">Login</h2>
    <form action="{% url 'login_user' %}" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" name="username" class="form-control" id="username" placeholder="Enter your username">
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" name="password" class="form-control" id="password" placeholder="Enter your password">
        </div>
        <div class="mb-3">
            <input type="submit" value="Login" class="bg-dark text-white text-center w-100 py-2">
        </div>
    </form>
</div>

{% endblock content %}

templates/accounts/manage_profile.html
{% extends 'base.html' %}


{% block title %}
    Manage Profile
{% endblock title %}
    

{% block content %}

<div class="container my-4">
   <h2 class="my-4">Manage your profile</h2>
   <form action="{% url 'manage_profile' %}" method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input type="text" name="username" class="form-control" id="username" 
        value="{{ user.username }}">
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email Address</label>
        <input type="email" name="email-address" class="form-control" id="email"
        value="{{ user.email }}">
    </div>
    <div class="mb-3">
        <label for="contact-no" class="form-label">Contact No</label>
        <input type="number" name="contact-no" class="form-control" id="contact-no"
        value="{{ user.contact_no }}">
    </div>
    <div class="mb-3">
        <label for="address" class="form-label">Address</label>
        <textarea name="address" class="form-control" id="address" rows="3">{{ user.address }}</textarea>
    </div>
    <!-- <div class="mb-3">
        <label for="password" class="form-label">Old Password</label>
        <input type="password" name="password" class="form-control" id="password"
        placeholder="Enter your old password">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">New Password</label>
        <input type="password" name="password" class="form-control" id="password"
        placeholder="Enter your new password">
    </div> -->
    <div class="mb-3">
        <input type="submit" value="Register" class="bg-dark text-white text-center w-100 py-2 my-4">
    </div>
</form>
</div>

{% endblock content %}

templates/accounts/manage_properties.html
{% extends 'base.html' %}


{% block title %}
    Manage Properties
{% endblock title %}
    
{% block content %}
    <div class="container my-4">
        <h2 class="text-center my-3">Manage Your Properties</h2>
        <div class="d-flex justify-content-center align-items-center flex-wrap">
            {% for property in owner_properties %}
            <div class="card m-3 position-relative">
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxuwwqhbenhtr_hPOkocblyV6wKAbOvfKY8g&s"
                    class="card-img-top" alt="property-image" width="10">
                <div class="card-body">
                    <div class="price-label">
                        {{ property.price }} / month
                    </div>
                    <h5 class="card-title">{{ property.property_title | title}}</h5>
                    <div class="d-flex justify-content-center align-items-center">
                        <div class="d-flex mx-1">
                            <p><i class="fa-solid fa-bed mx-1"></i></p>
                            <p>{{ property.bedrooms }} Beds</p>
                        </div>
    
                        <div class="d-flex justify-content-center align-items-center mx-1 my-3">
                            <p><i class="fa-solid fa-bath mx-1"></i></p>
                            <p>{{ property.bathrooms }} Baths</p>
                        </div>
    
                        <div class="d-flex mx-1">
                            <p><i class="fa-solid fa-chart-area mx-1"></i></p>
                            <p>{{ property.sqft }} Sqft</p>
                        </div>
                    </div>
                    <hr class="w-100">
    
                    <div class="d-flex justify-content-between">
                        <!-- <p><i class="fa-solid fa-location-dot"></i> {{ property.address | title }} </p> -->
                        <a href="{% url 'property' property.id  %}"><button class="btn btn-dark mx-2">View</button></a>
                        <a href="{% url 'update_property' property.id  %}"><button class="btn btn-primary mx-2">Update</button></a>
                        <a data-propertyid="{{ property.id }}" class="delete-btns"><button class="btn btn-danger mx-2">Delete</button></a>
                        <a data-propertyid="{{ property.id }}" class="booked-btns"><button class="btn btn-success mx-2">Booked</button></a>
                    </div>
    
                </div>
            </div>
            {% endfor %}
            
        </div>
    </div>
</div>
    
{% endblock content %}

templates/accounts/owner_registration.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-4">
    <h2 class="my-3">Owner Registration</h2>
    <form action="{% url 'owner_registration' %}" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" name="username" class="form-control" id="username" placeholder="Enter your username">
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">Email Address</label>
            <input type="email" name="email-address" class="form-control" id="email"
                placeholder="Enter your email address">
        </div>
        <div class="mb-3">
            <label for="contact-no" class="form-label">Contact No</label>
            <input type="number" name="contact-no" class="form-control" id="contact-no"
                placeholder="Enter contact number">
        </div>
        <div class="mb-3">
            <label for="address" class="form-label">Address</label>
            <textarea name="address" class="form-control" id="address" rows="3"
                placeholder="Enter your address"></textarea>
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" name="password" class="form-control" id="password" placeholder="Enter your password">
        </div>
        <div class="mb-3">
            <label for="cpassword" class="form-label">Confirm Password</label>
            <input type="password" name="cpassword" class="form-control" id="cpassword"
                placeholder="Enter the same password again">
        </div>
        <div class="mb-3">
            <input type="submit" value="Register" class="bg-dark text-white text-center w-100 py-2">
        </div>
    </form>
</div>

{% endblock content %}

templates/accounts/recieved_enquiries.html
{% extends 'base.html' %}


{% block title %}
    Recieved Enquiries
{% endblock title %}
    

{% block content %}
<div class="container my-4">
    <h2 class="my-4">Recieved Enquiries</h2>
    
    {% if enquiries %}
      <table class="table my-4">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Email Address</th>
            <th scope="col">Contact No</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
            {% for enquiry in enquiries %}
          <tr>
            <th scope="row">{{ enquiry.id }}</th>
            <td>{{ enquiry.user_id.username }}</td>
            <td>{{ enquiry.user_id.email }}</td>
            <td>{{ enquiry.user_id.contact_no }}</td>
            <td><a href="{% url 'enquiry_details' enquiry.id %}"><button type="button" class="btn btn-light">View Detail</button></a></td>
          </tr>
          {% endfor %}

        </tbody>
      </table>

    {% else %}
      <p class="bg-dark text-white py-2 px-4 text-center">No enquiries recieved up untill now</p>

    {% endif %}
      
   
</div>
{% endblock content %}

templates/accounts/send_enquiries.html
{% extends 'base.html' %}


{% block title %}
    Send Enquiries
{% endblock title %}
    

{% block content %}

<div class="container my-4">
    <h2 class="my-4">Your send enquiries</h2>
    
    {% if enquiries %}
                
        <table class="table my-4">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Property Name</th>
                <th scope="col">Property Address</th>
                <th scope="col">Property Price</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            {% for enquiry in enquiries %}
                <tr>
                    <th scope="row">{{ enquiry.id }}</th>
                    <td>{{ enquiry.property_id.property_title }}</td>
                    <td>{{ enquiry.property_id.address }}</td>
                    <td>{{ enquiry.property_id.price }}</td>
                    <td><a href="{% url 'property' enquiry.property_id.id %}"><button type="button" class="btn btn-light">View Property</button></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    {% else %}
        <p class="bg-dark text-white py-2 px-4 text-center">You haven't made any enquiry</p>
    {% endif %}

</div>

{% endblock content %}

templates/accounts/update_property.html
{% extends 'base.html' %}


{% block title %}
    Update Property
{% endblock title %}
    

{% block content %}

<div class="container my-4">
    <h2 class="my-4">Update your Property</h2>
    <form action="{% url 'update_property' updated_property.id %}" method="POST" enctype="multipart/form-data" class="d-flex flex-column">
        {% csrf_token %}
     <label for="id_property_title">Property title:</label>
     <input type="text" name="property_title" value="{{ updated_property.property_title }}" class="form-control" maxlength="200" required="" id="id_property_title">

     <label for="id_bathrooms">Bathrooms:</label>
     <input type="number" name="bathrooms" value="{{ updated_property.bathrooms }}" class="form-control" required="" id="id_bathrooms">
     
     <label for="id_bedrooms">Bedrooms:</label>
     <input type="number" name="bedrooms" value="{{ updated_property.bedrooms }}" class="form-control" required="" id="id_bedrooms">
     
     <label for="id_rooms">Rooms:</label>
     <input type="number" name="rooms" value="{{ updated_property.rooms }}" class="form-control" required="" id="id_rooms">
     <label for="id_price">Price:</label>
     <input type="number" name="price" value="{{ updated_property.price }}" class="form-control" required="" id="id_price">
     
     <label for="id_garage">Garage:</label>
     <input type="number" name="garage" value="{{ updated_property.garage }}" value="0" class="form-control" required="" id="id_garage">
     
     <label for="id_address">Address:</label>
     <input type="text" name="address" value="{{ updated_property.address }}" class="form-control" maxlength="200" required="" id="id_address">
     
     <label for="id_city">City:</label>
     <input type="text" name="city" value="{{ updated_property.city }}" class="form-control" maxlength="100" required="" id="id_city">
    
     <label for="id_state">State:</label>
     <input type="text" name="state" value="{{ updated_property.state }}" class="form-control" maxlength="100" required="" id="id_state">
         
     <label for="id_zipcode">Zipcode:</label>
     <input type="text" name="zipcode" value="{{ updated_property.zipcode }}" class="form-control" maxlength="20" required="" id="id_zipcode">
     <label for="id_sqft">Sqft:</label>
     <input type="number" name="sqft" value="{{ updated_property.sqft }}" class="form-control" step="0.1" required="" id="id_sqft">
    
     <label for="id_main_image">Main image:</label>
     <input type="file" name="main_image" value="{{ updated_property.main_image.url }" class="form-control" required="" id="id_main_image">

     <label for="id_image_1">Image 1:</label>
     <input type="file" name="image_1" value="{{ updated_property.image_1.url }}" class="form-control" required="" id="id_image_1">

     <label for="id_image_2">Image 2:</label>
     <input type="file" name="image_2" value="{{ updated_property.image_2.url }}" class="form-control" required="" id="id_image_2">
     
     <label for="id_image_3">Image 3:</label>
     <input type="file" name="image_3" value="{{ updated_property.image_3.url }}" class="form-control" required="" id="id_image_3">
     
     <label for="id_wifi">Wifi:</label>
     <input type="checkbox" name="wifi" {% if updated_property.wifi %} checked {% endif %} id="id_wifi">
     
     <label for="id_kitchen">Kitchen:</label>
     <input type="checkbox" name="kitchen" {% if updated_property.kitchen %} checked {% endif %} id="id_kitchen">
     
     <label for="id_parking">Parking:</label>
     <input type="checkbox" name="parking" {% if updated_property.parking %} checked {% endif %} id="id_parking">
     
     <label for="id_swimming_pool">Swimming pool:</label>
     <input type="checkbox" name="swimming_pool" {% if updated_property.swimming_pool %} checked {% endif %} id="id_swimming_pool">
     
     <label for="id_air_conditioning">Air conditioning:</label>
     <input type="checkbox" name="air_conditioning" {% if updated_property.air_conditioning %} checked {% endif %} id="id_air_conditioning">
     
     <label for="id_balcony">Balcony:</label>
     <input type="checkbox" name="balcony" {% if updated_property.balcony %} checked {% endif %} id="id_balcony">

     <label for="id_tv">Tv:</label>
     <input type="checkbox" name="tv" {% if updated_property.tv %} checked {% endif %} id="id_tv">  
  
     <label for="id_laundry">Laundry:</label>
     <input type="checkbox" name="laundry" {% if updated_property.laundry %} checked {% endif %} id="id_laundry">
   
     <label for="id_elevator_access">Elevator access:</label>
     <input type="checkbox" name="elevator_access" {% if updated_property.elavator_access %} checked {% endif %} id="id_elevator_access">

     <input type="submit" class="bg-dark text-white text-center py-2 w-100 my-3" value="Update Property">
    </form>
 </div>

{% endblock content %}

templates/accounts/user_registration.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-4">
    <h2 class="my-3">User Registration</h2>
    <form action="{% url 'user_registration' %}" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" name="username" class="form-control" id="username" placeholder="Enter your username">
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">Email Address</label>
            <input type="email" name="email-address" class="form-control" id="email"
                placeholder="Enter your email address">
        </div>
        <div class="mb-3">
            <label for="contact-no" class="form-label">Contact No</label>
            <input type="number" name="contact-no" class="form-control" id="contact-no"
                placeholder="Enter contact number">
        </div>
        <div class="mb-3">
            <label for="address" class="form-label">Address</label>
            <textarea name="address" class="form-control" id="address" rows="3"
                placeholder="Enter your address"></textarea>
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" name="password" class="form-control" id="password" placeholder="Enter your password">
        </div>
        <div class="mb-3">
            <label for="cpassword" class="form-label">Confirm Password</label>
            <input type="password" name="cpassword" class="form-control" id="cpassword"
                placeholder="Enter the same password again">
        </div>
        <div class="mb-3">
            <input type="submit" value="Register" class="bg-dark text-white text-center w-100 py-2">
        </div>
    </form>
</div>

{% endblock content %}